// Bundles the browser-side map runtime (including MapLibre GL JS) into a single
// IIFE, then writes it as a TypeScript constant file for inclusion in the plug.
import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");

const result = await esbuild.build({
	entryPoints: [path.join(rootDir, "src/runtime/entry.ts")],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2020",
	minify: true,
	write: false,
	define: {
		"process.env.NODE_ENV": '"production"',
	},
});

const jsBundle = result.outputFiles[0].text;

const cssPath = path.join(
	rootDir,
	"node_modules/maplibre-gl/dist/maplibre-gl.css",
);
const cssContent = fs.readFileSync(cssPath, "utf-8");

const output = [
	"// AUTO-GENERATED by scripts/build-runtime.mjs — do not edit manually",
	`export const RUNTIME_BUNDLE = ${JSON.stringify(jsBundle)};`,
	`export const RUNTIME_CSS = ${JSON.stringify(cssContent)};`,
].join("\n") + "\n";

const outputPath = path.join(rootDir, "src/runtime/generated-bundle.ts");
fs.writeFileSync(outputPath, output);

console.log(
	`Runtime bundle generated: ${jsBundle.length} bytes JS, ${cssContent.length} bytes CSS`,
);
